// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: abi.proto

package abi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resize_ResizeType int32

const (
	Resize_Lanczos    Resize_ResizeType = 0
	Resize_CatmullRom Resize_ResizeType = 1
	Resize_Linear     Resize_ResizeType = 2
	Resize_Box        Resize_ResizeType = 3
)

// Enum value maps for Resize_ResizeType.
var (
	Resize_ResizeType_name = map[int32]string{
		0: "Lanczos",
		1: "CatmullRom",
		2: "Linear",
		3: "Box",
	}
	Resize_ResizeType_value = map[string]int32{
		"Lanczos":    0,
		"CatmullRom": 1,
		"Linear":     2,
		"Box":        3,
	}
)

func (x Resize_ResizeType) Enum() *Resize_ResizeType {
	p := new(Resize_ResizeType)
	*p = x
	return p
}

func (x Resize_ResizeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resize_ResizeType) Descriptor() protoreflect.EnumDescriptor {
	return file_abi_proto_enumTypes[0].Descriptor()
}

func (Resize_ResizeType) Type() protoreflect.EnumType {
	return &file_abi_proto_enumTypes[0]
}

func (x Resize_ResizeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resize_ResizeType.Descriptor instead.
func (Resize_ResizeType) EnumDescriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{1, 0}
}

type Specs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Specs []*Spec `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
}

func (x *Specs) Reset() {
	*x = Specs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specs) ProtoMessage() {}

func (x *Specs) ProtoReflect() protoreflect.Message {
	mi := &file_abi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specs.ProtoReflect.Descriptor instead.
func (*Specs) Descriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{0}
}

func (x *Specs) GetSpecs() []*Spec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  uint32            `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32            `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Rtype  Resize_ResizeType `protobuf:"varint,3,opt,name=rtype,proto3,enum=abi.Resize_ResizeType" json:"rtype,omitempty"`
}

func (x *Resize) Reset() {
	*x = Resize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_abi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{1}
}

func (x *Resize) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resize) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Resize) GetRtype() Resize_ResizeType {
	if x != nil {
		return x.Rtype
	}
	return Resize_Lanczos
}

type Blur struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigma float64 `protobuf:"fixed64,1,opt,name=sigma,proto3" json:"sigma,omitempty"`
}

func (x *Blur) Reset() {
	*x = Blur{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blur) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blur) ProtoMessage() {}

func (x *Blur) ProtoReflect() protoreflect.Message {
	mi := &file_abi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blur.ProtoReflect.Descriptor instead.
func (*Blur) Descriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{2}
}

func (x *Blur) GetSigma() float64 {
	if x != nil {
		return x.Sigma
	}
	return 0
}

type Brightness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brightness float64 `protobuf:"fixed64,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
}

func (x *Brightness) Reset() {
	*x = Brightness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Brightness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brightness) ProtoMessage() {}

func (x *Brightness) ProtoReflect() protoreflect.Message {
	mi := &file_abi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brightness.ProtoReflect.Descriptor instead.
func (*Brightness) Descriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{3}
}

func (x *Brightness) GetBrightness() float64 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type Contrast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contrast float64 `protobuf:"fixed64,1,opt,name=contrast,proto3" json:"contrast,omitempty"`
}

func (x *Contrast) Reset() {
	*x = Contrast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contrast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contrast) ProtoMessage() {}

func (x *Contrast) ProtoReflect() protoreflect.Message {
	mi := &file_abi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contrast.ProtoReflect.Descriptor instead.
func (*Contrast) Descriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{4}
}

func (x *Contrast) GetContrast() float64 {
	if x != nil {
		return x.Contrast
	}
	return 0
}

type Gamma struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gamma float64 `protobuf:"fixed64,1,opt,name=gamma,proto3" json:"gamma,omitempty"`
}

func (x *Gamma) Reset() {
	*x = Gamma{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gamma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gamma) ProtoMessage() {}

func (x *Gamma) ProtoReflect() protoreflect.Message {
	mi := &file_abi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gamma.ProtoReflect.Descriptor instead.
func (*Gamma) Descriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{5}
}

func (x *Gamma) GetGamma() float64 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Spec_Resize
	//	*Spec_Blur
	//	*Spec_Brightness
	//	*Spec_Contrast
	//	*Spec_Gamma
	Data isSpec_Data `protobuf_oneof:"data"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_abi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_abi_proto_rawDescGZIP(), []int{6}
}

func (m *Spec) GetData() isSpec_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Spec) GetResize() *Resize {
	if x, ok := x.GetData().(*Spec_Resize); ok {
		return x.Resize
	}
	return nil
}

func (x *Spec) GetBlur() *Blur {
	if x, ok := x.GetData().(*Spec_Blur); ok {
		return x.Blur
	}
	return nil
}

func (x *Spec) GetBrightness() *Brightness {
	if x, ok := x.GetData().(*Spec_Brightness); ok {
		return x.Brightness
	}
	return nil
}

func (x *Spec) GetContrast() *Contrast {
	if x, ok := x.GetData().(*Spec_Contrast); ok {
		return x.Contrast
	}
	return nil
}

func (x *Spec) GetGamma() *Gamma {
	if x, ok := x.GetData().(*Spec_Gamma); ok {
		return x.Gamma
	}
	return nil
}

type isSpec_Data interface {
	isSpec_Data()
}

type Spec_Resize struct {
	Resize *Resize `protobuf:"bytes,1,opt,name=resize,proto3,oneof"`
}

type Spec_Blur struct {
	Blur *Blur `protobuf:"bytes,2,opt,name=blur,proto3,oneof"`
}

type Spec_Brightness struct {
	Brightness *Brightness `protobuf:"bytes,3,opt,name=brightness,proto3,oneof"`
}

type Spec_Contrast struct {
	Contrast *Contrast `protobuf:"bytes,4,opt,name=contrast,proto3,oneof"`
}

type Spec_Gamma struct {
	Gamma *Gamma `protobuf:"bytes,5,opt,name=gamma,proto3,oneof"`
}

func (*Spec_Resize) isSpec_Data() {}

func (*Spec_Blur) isSpec_Data() {}

func (*Spec_Brightness) isSpec_Data() {}

func (*Spec_Contrast) isSpec_Data() {}

func (*Spec_Gamma) isSpec_Data() {}

var File_abi_proto protoreflect.FileDescriptor

var file_abi_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x62, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x62, 0x69,
	0x22, 0x28, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x70, 0x65,
	0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x62, 0x69, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x05, 0x73, 0x70, 0x65, 0x63, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x72, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x61, 0x62, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x72, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x3e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x4c, 0x61, 0x6e, 0x63, 0x7a, 0x6f, 0x73, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x61, 0x74, 0x6d, 0x75, 0x6c, 0x6c, 0x52, 0x6f, 0x6d, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x6f, 0x78, 0x10,
	0x03, 0x22, 0x1c, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x67,
	0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x22,
	0x2c, 0x0a, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x26, 0x0a,
	0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x05, 0x47, 0x61, 0x6d, 0x6d, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x67, 0x61, 0x6d, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x67,
	0x61, 0x6d, 0x6d, 0x61, 0x22, 0xda, 0x01, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x25, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x61, 0x62, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x62, 0x6c, 0x75, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x62, 0x69, 0x2e, 0x42, 0x6c, 0x75, 0x72, 0x48, 0x00, 0x52,
	0x04, 0x62, 0x6c, 0x75, 0x72, 0x12, 0x31, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x62, 0x69, 0x2e,
	0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x62, 0x69,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x6d, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x62, 0x69, 0x2e, 0x47, 0x61, 0x6d, 0x6d, 0x61,
	0x48, 0x00, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x6d, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x62, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_abi_proto_rawDescOnce sync.Once
	file_abi_proto_rawDescData = file_abi_proto_rawDesc
)

func file_abi_proto_rawDescGZIP() []byte {
	file_abi_proto_rawDescOnce.Do(func() {
		file_abi_proto_rawDescData = protoimpl.X.CompressGZIP(file_abi_proto_rawDescData)
	})
	return file_abi_proto_rawDescData
}

var file_abi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_abi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_abi_proto_goTypes = []interface{}{
	(Resize_ResizeType)(0), // 0: abi.Resize.ResizeType
	(*Specs)(nil),          // 1: abi.Specs
	(*Resize)(nil),         // 2: abi.Resize
	(*Blur)(nil),           // 3: abi.Blur
	(*Brightness)(nil),     // 4: abi.Brightness
	(*Contrast)(nil),       // 5: abi.Contrast
	(*Gamma)(nil),          // 6: abi.Gamma
	(*Spec)(nil),           // 7: abi.Spec
}
var file_abi_proto_depIdxs = []int32{
	7, // 0: abi.Specs.specs:type_name -> abi.Spec
	0, // 1: abi.Resize.rtype:type_name -> abi.Resize.ResizeType
	2, // 2: abi.Spec.resize:type_name -> abi.Resize
	3, // 3: abi.Spec.blur:type_name -> abi.Blur
	4, // 4: abi.Spec.brightness:type_name -> abi.Brightness
	5, // 5: abi.Spec.contrast:type_name -> abi.Contrast
	6, // 6: abi.Spec.gamma:type_name -> abi.Gamma
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_abi_proto_init() }
func file_abi_proto_init() {
	if File_abi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_abi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blur); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Brightness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contrast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gamma); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_abi_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Spec_Resize)(nil),
		(*Spec_Blur)(nil),
		(*Spec_Brightness)(nil),
		(*Spec_Contrast)(nil),
		(*Spec_Gamma)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_abi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abi_proto_goTypes,
		DependencyIndexes: file_abi_proto_depIdxs,
		EnumInfos:         file_abi_proto_enumTypes,
		MessageInfos:      file_abi_proto_msgTypes,
	}.Build()
	File_abi_proto = out.File
	file_abi_proto_rawDesc = nil
	file_abi_proto_goTypes = nil
	file_abi_proto_depIdxs = nil
}
